### ISSUE TITLE
Invoking PowerShell opens a command line window

### ISSUE THREAD

**Issue by Bios-Marcel** [Bios-Marcel/wastebasket#2]
Sadly Windows PowerShell doesn't have any headless executable, therefore it always opens a commandline window, unless started from the commandline anyway.

The solution would be use the win32 API instead.

See:
* Trash
  * https://docs.microsoft.com/en-gb/windows/desktop/api/shobjidl_core/nf-shobjidl_core-ifileoperation-deleteitem
  * https://docs.microsoft.com/en-gb/windows/desktop/api/shobjidl_core/nf-shobjidl_core-ifileoperation-performoperations
* Empty
  * https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shemptyrecyclebinw
  * https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-shemptyrecyclebina

**Comment by Bios-Marcel** [comment]
My unit tests were incorrect and deleting files doesn't seem to work properly on windows. I'll now reimplement the functionally by calling the win32 api.

**Comment by Stoyvo** [comment]
Looking forward to seeing this! Do you have a branch where this is started? If I have free time I wouldn't mind poking this

**Comment by Bios-Marcel** [comment]
Uhm no, haven't started that yet, since I don't have a windows installation. I'd be happy if someone were to solve this.

**Comment by Bios-Marcel** [comment]
Fixed with:

* c81dcaa651ffcce340fad58c973e193cd93f7b2d
* 49db11b403eed714a3f8c04a2f7cec2f5667da32
* 32bc55a4fb01f8739d365e2b7c03b046a16828d5
