### ISSUE TITLE
Remove unneeded println from wastebasket_windows.go

### ISSUE THREAD

**Issue by lcserny** [Bios-Marcel/wastebasket#3]
Hi, can you please remove the `fmt.Println(psCommand)` line in the wastebasket_windows.go file?
I am using your repo for a command line app which needs StdOut and StdErr to be clean, and that println statement pollutes it.
Thanks!

**Comment by Bios-Marcel** [comment]
Oh, I did that by accident. I'll do that as soon as I am home.

**Comment by Bios-Marcel** [comment]
Done!
